backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "team"
    label: "Team"
    folder: "src/content/team"
    create: true
    slug: "{{slug}}"
    editor:
     preview: false
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Twitter", name: "twitter", widget: "string" }
      - { label: "Instagram", name: "instagram", widget: "string" }
      - { label: "Weight", name: "weight", widget: "number" }
      - { label: "Bio", name: "body", widget: "markdown" }
