backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "team"
    label: "Team"
    folder: "src/content/team"
    create: true
    slug: "{{slug}}"
    editor:
     preview: false
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Headshot", name: "featuredImage", widget: "image" }
      - { label: "Twitter", name: "twitter", widget: "string" }
      - { label: "Instagram", name: "instagram", widget: "string" }
      - { label: "Weight", name: "weight", widget: "number" }
      - { label: "Bio", name: "body", widget: "markdown" }
  - name: "portfolio"
    label: "Portfolio"
    folder: "src/content/portfolio"
    create: true
    slug: "{{slug}}"
    editor:
     preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Clients", name: "clients", widget: "list"}
      - { label: "YouTube Link", name: "youtubeLink", widget: "string", required: false}
      - { label: "External Link", name: "externalLink", widget: "string", required: false}
      - { label: "Type", name: "type", widget: "string"}